necolas/normalize.css

- normalize.css
- test.html
As issues #349 and #339 explain, color inheritance applied to form elements creates some possible usability issues in certain scenarios (see http://codepen.io/anon/pen/FyhsL), and causes disabled form elements to appear as though they are enabled.
This removes the `color: inherit;` declaration and subsequent test to alleviate those issues.
> Disabled element color inheritance

- index.html
Bower and Component installation support was dropped in 8cfa3e765e0cb55c174657e412430424a9fee97a.
> Remove Bower and Component installation

- normalize.css
I've checked issue with `<audio>` without controls in all browsers available at http://crossbrowsertesting.com and find out that this issue take place only in Mobile Safari 4—7.
This is final codepen I've using for checking the bug: http://codepen.io/hudochenkov/pen/mVzpzL.
This is results with iOS (other browsers I've not included here, because they don't have issues):
[Screenshots](https://app.crossbrowsertesting.com/public/i1769107ade2a10c/screenshots/zdd8e3b5120ca708a264) for: 
```css
audio:not([controls]) {
background: red;
}
```
[Screenshots](https://app.crossbrowsertesting.com/public/i1769107ade2a10c/screenshots/z82aaf7a774911d37ae7) for: 
```css
audio:not([controls]) {
background: red;
display: none;
}
```
[Screenshots](https://app.crossbrowsertesting.com/public/i1769107ade2a10c/sc …
> Specify browsers for displaying `audio` without controls issue

- .travis.yml
Since this repository was not recognized by Travis before 2015-01-01, there is no need to include `sudo: false` as that is now the default.
--
From https://docs.travis-ci.com/user/workers/container-based-infrastructure/#Routing-your-build-to-container-based-infrastructure:
> The default behavior, when no sudo usage is detected in any customizable build phases, depends on the date when the repository is first recognized by Travis CI:
> * For repos we recognize before 2015-01-01, linux builds are sent to our standard infrastructure.
> * For repos we recognize on or after 2015-01-01, linux builds are sent to our container-based infrastructure "
> Remove `sudo: false` from `.travis.yml`

- README.md
Since Bower **explicit support** was removed on 8cfa3e765e0cb55c174657e412430424a9fee97a many people complained about this.
I think that by clearly indicating the way to install normalize.css using Bower will help to reduce the number of comments/open-issues about that, and of course, help those that don't know how to install an unregistered package.
*This closes #527*
> Add Bower install details

- normalize.css
The `font-family: sans-serif` in the `html` [[1](https://github.com/necolas/normalize.css/blob/3.0.3/test.html#L89)] and `margin: 0` in the `body` [[2](https://github.com/necolas/normalize.css/blob/3.0.3/test.html#L95)] are opinionated declarations, thus marked as such.
*This closes #517 and #518.*
> Mark opinionated styles

- normalize.css
By using `outline-width` we are explicit in our intention.
Also as this is an [opinionated style](https://github.com/necolas/normalize.css/blob/3.0.3/test.html#L153), it's now marked as such.
*This closes #524.*
> Use explicit `outline-width` property instead of `outline`

- normalize.css
Use inherit to fix legend color and clarify that the fix applies to `<legend>` within `<fieldset>`.
This closes #363.
> Use inherit to fix legend color

- normalize.css
- test.html
The `line-height` issue was resolved in Firefox 30, so this normalization may be dropped.
Resolves #377
> Remove unnecessary input line-height

- normalize.css
**Chrome 16+**, **Edge 12+**, **Firefox 4+**, **Internet Explorer 6+**, **Opera 12.12+**, and **Safari 6+**. Only **Safari ≤ 5.1** is missing the style, which has not been in the supported browser stack of normalize.css v3.
Resolves #522
> Update the dfn support message

- normalize.css
Correct `border-style` given when inside `a` element in IE 8/9/10. See http://s.codepen.io/jonneal/debug/274c26a11e945ee932aa1f32512d48e6
> Only normalize border-style on img

- normalize.css
- test.html
Corrects `<legend>` wrapping not present in IE8-11 and Edge 12-13. It actually requires 2 separate fixes in order to work in both IE8 and Edge 13.
`box-sizing: border-box` and `max-width: 100%` correct the issue in IE9-11 as well as Edge 12-13, while `display: table` and `white-space: normal` correct the issue in IE8-11.
Resolves #100
> Correct wrapping not present in IE8/9/10/11 and Edge 12/13

- normalize.css
- Moves input type appearance normalization into its own rule.
- Reduces selector weight of input types.
Resolves #438
> Reduce input type selector weight

- normalize.css
- test.html
This removes the opinionated view that `pre` should contain its overflow.
Not necessary to merge unless there is more consensus.
Resolves #313
> Remove opinionated pre overflow

- CONTRIBUTING.md
- Remove `v1` references since it's not is no longer actively developed.
*Other minor changes:*
- Remove duplicated `git pull --rebase upstream master` instruction.
- Wrapt text to 80 columns.
---
*Feel free to ignore.*
> Remove `v1` references

- normalize.css
While the consistent `overflow` for `select` is `visible`, updating this property has no effect in any browser, but instead creates an inappropriately visible overflow for `select[multiple]`.
Resolves #562
> Remove overflow from select and update multiple overflow

- normalize.css
Normalizes placeholder styles in Edge, Chrome, and Safari with Firefox.
Resolves #550
> Correct the text style of placeholders in Chrome, Edge, and Safari

- normalize.css
Spacing does not need to be normalized for all `input` elements in
Firefox, only `button` and `[type="button"]` elements. These
normalizations were changing the default focus appearance of `input`
elements.
Resolves #549
> Limit Firefox focus normalization to buttons

- normalize.css
Remove gaps in links underline in iOS 8+ and Safari 8+
This gaps presented in Safari and iOS only. They were added in Safari 8 and iOS 8 but CrossBrowserTesting show them even in Safari 6.
[CodePen without fix](http://codepen.io/hudochenkov/pen/RaxqNW) and [results](https://app.crossbrowsertesting.com/public/i1769107ade2a10c/screenshots/z894d678ffb8d28e7e2b).
[CodePen with fix](http://codepen.io/hudochenkov/pen/groQbM) and [results](https://app.crossbrowsertesting.com/public/i1769107ade2a10c/screenshots/z5cba15df917b55d4a30).
> Remove gaps in links underline in iOS 8+ and Safari 8+

- normalize.css
After modifying search input with -webkit-appearance: textfield, the
focus outline is remaining with `outline-offset: 0`, but should be
`-2px` like other textfield inputs.
Resolves #547
> Correct the outline of search inputs in Chrome and Safari

- normalize.css
> In the same way you are setting -webkit-appearance:button in line 299, i think you should do the same for the "select file" button present in file fields, in order to keep a uniform aspect between all fields in Safari:
Resolves #570
> Normalize file select buttons

- normalize.css
Line heights are different between almost any browser out there for all heading tags, the majority of them apply a `1.15` to `line-height` property. For more insight check out the issue #593 
This is ready for review, @jonathantneal
> Normalize line heights for all headings

- normalize.css
The results for computed `line-height` in #593 were virtually different in all tested browsers, and since [such browsers are the ones we support](https://github.com/necolas/normalize.css#browser-support), I don't see the need to have a *complex* comment naming all of them. Also, having the "headings" reference is redundant, since by looking at the selectors is clear what we are targeting.
I know this is kinda silly, but it's important to keep comments short and to the point. 😉
> Simplify headings normalization comment

- normalize.css
We can not safely normalize the `placeholder` without introducing a specific color —which would be very opinionated—, or without modifying the `opacity` —which would prevent the placeholder from being shown in Edge under certain conditions [due to a bug](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/3901363/).
*Context*: this was originally discussed on #550 and then added on #571. The decision to remove it was made on #580.
*Notes*: (a) I didn't modify the `test.html` file since I couldn't find a test for this. (b) I didn't add a note to the README as @jonathantneal suggested since as we no longer include this, it would be weird to add it to a section with the "additional detail and explanation of the esoteric parts of normalize.css." tagline —please, feel free to …
> Remove `placeholder` normalization

- CHANGELOG.md
- normalize.css
- test.html
Resolves #591 by explicitly setting `font-family`, `font-size`, and `line-height` rather than using `inherit`.
^ @battaglr, also see the `line-height` tests in the related issue.
> More explicitly define font resets on form controls

- index.html
Noticed the website isn't pointing to the latest normalize.css version, just simply changes the hardtext & links.
> Change latest it v4.2.0

- package.json
`#readme` ID isn't present anymore.
> Update homepage URL

- normalize.css
- Remove changing the default font family in all browsers.
- Remove the removal of margin on body in all browsers.
- Remove the removal of outline on focused links when they are also
active or hovered in all browsers (opinionated).
- Remove changing the font styles of input controls in all browsers.
- Remove the changing of border, margin, and padding of fieldsets in
all browsers.
> Remove all opinionated rules

- .gitattributes
Small fix to correct this repository's [language breakdown graph](https://github.com/necolas/normalize.css/search?l=html).
Since Normalize.css is [purposefully excluded](https://github.com/github/linguist/blob/master/lib/linguist/vendor.yml#L73) from language stats on GitHub, a `.gitattributes` file is needed to include it in the languages breakdown. Currently, the codebase is marked as 100% HTML.
More info on the `linguist-vendored` attribute [here](https://github.com/github/linguist#using-gitattributes).
> Fix repository's language classification on GitHub

- .gitattributes
I really should've paid more attention before submitting #660...
This PR finishes off what #660 should've done by excluding [`test.html`](https://github.com/necolas/normalize.css/blob/master/test.html) from the repository's language breakdown. It's common practice in many GitHub repos to mark test files with the [`linguist-documentation`](https://github.com/github/linguist/blob/master/lib/linguist/documentation.yml) attribute.
This is identical to [`linguist-vendored`](https://github.com/github/linguist#using-gitattributes) in that it stops marked files from skewing language stats... the key difference being that "documentation" files are included in diffs on GitHub, whereas vendored files aren't. Test-related files are the sort of thing that you don't want bloating language stats, but …
> Stop test.html from skewing language classification

- normalize.css
v6 has removed the opinionated styling for the `fieldset` element.
One of the removed rules was the padding, and I noticed that this introduced a little inconsistency between firefox and other browsers.
In my test, I saw consistent padding in chrome and IE. But a slightly different padding in Firefox.
Firefox
Chrome
> Fieldset padding in firefox

- normalize.css
#573 introduced the change. I propose to revert it, because:
1. It breaks iOS and macOS platform conventions: underlines are always drawn with “ink” style in native text views.
2. It’s a step back for web typography. Apple intentionally set the browser default to “ink” to make underlined text more readable.
3. The lack of this rule doesn’t affect other browsers, but its presence is harmful.
> Restore gaps in links underline in iOS 8+ and Safari 8+
